exports.ERR_CODE_400 = "Invalid Request, check Syntax";
exports.ERR_PEER_NOT_SPECIFIED = "Please provide peer info";
exports.ERR_FILE_NOT_FOUND = "Retrieve Restaurant Menu null from DB: ";
exports.ERR_PEER_NOT_INSERTED = "Cannot insert peer into DB";
exports.INVALID_MENU_ITEM = "Invalid Menu Item, check Syntax";
exports.CANNOT_FIND_FBUSER = "Invalid Token, Check Syntax";
exports.FRIENDS_SUCCESS_CODE = "Friends Success";
exports.FRIENDS_FAIL_CODE = "Friends Fail";
exports.LOGIN_SUCCESS_CODE = "Login Success";